kashti:
  enabled: true
  service:
    type: NodePort
  ingress:
    enabled: true
    hosts:
      - kashti.brigade.homelab.evdev.me
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    tls:
    - hosts:
      - kashti.brigade.homelab.evdev.me
      secretName: brigade-kashti-tls
brigade-github-app:
  enabled: true
  service:
    type: NodePort
  ingress:
    hosts:
      - github-app.brigade.homelab.evdev.me
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    tls:
    - hosts:
      - github-app.brigade.homelab.evdev.me
      secretName: brigade-github-app-tls
  github:
    appID: 77268
worker:
  defaultBuildStorageClass: microk8s-hostpath
  defaultCacheStorageClass: microk8s-hostpath